#!/bin/bash -e

##############################################################################
###
### xubuntu_retropie (c)2023 xovox - https://github.com/xovox/RetroPie-xubuntu
###
### 
###
##############################################################################

sudocfg="$USER ALL=(ALL) NOPASSWD:ALL"
sudofile="/etc/sudoers.d/retropie-$USER"
autostartdir="$HOME/.config/autostart"

retropie_git="https://github.com/retropie/RetroPie-Setup"

retropie_remove="
	lr-mame2003
	mupen64plus
"

retropie_install="
	lr-bluemsx
	lr-freeintv
	lr-mame2003-plus
	lr-mupen64plus
	lr-neocd
	scraper
"

required_packages="
	ffmpeg
	git
"

##############################################################################
# xfce4 configuration settings
##############################################################################

declare -A xfwm4=(
	[theme]="Greybird-compact"
)

declare -A xfce4_power_manager=(
	[power-button-action]="4"
	[blank-on-ac]="0"
	[lock-screen-suspend-hibernate]="false"
	[dpms-enabled]="false"
	[dpms-on-ac-sleep]="0"
	[dpms-on-ac-off]="0"
)

declare -A xfce4_screensaver=(
	[/lock/enabled]="false"
	[/lock/saver-activation/enabled]="false"
	[/saver/enabled]="false"
	[/saver/idle-activation/enabled]="false"
	[/saver/mode]="0"
)


##############################################################################
# upgrade os & install requirements
##############################################################################

sudo apt update
sudo apt -y dist-upgrade
sudo apt -y install $required_packages

##############################################################################
# configure xfce4
##############################################################################

for setting in "${!xfwm4[@]}"; do
	xfconf-query -v -c xfwm4 -p /general/$setting -s ${xfwm4[$setting]}
done

for setting in "${!xfce4_power_manager[@]}"; do
	xfconf-query -v -c xfce4-power-manager -p /xfce4-power-manager/$setting -s ${xfce4_power_manager[$setting]}
done

for setting in "${!xfce4_screensaver[@]}"; do
	xfconf-query -v -c xfce4-screensaver -p $setting -s ${xfce4_screensaver[$setting]}
done

##############################################################################
# configure sudo
##############################################################################

echo "$sudocfg" | sudo tee $sudofile
sudo chmod -c 0400 $sudofile

##############################################################################
# clone and build retropie
##############################################################################

git -C $HOME clone $retropie_git

cd $HOME/RetroPie-Setup

sudo ./retropie_packages.sh setup basic_install

##############################################################################
# remove unfriendly/outdated packages
##############################################################################

for retropie_package in $retropie_remove ; do
	sudo ./retropie_packages.sh $retropie_package remove
done

##############################################################################
# install additional emulators
##############################################################################

for retropie_package in $retropie_install ; do
	for act in depends sources build install configure ; do
		sudo ./retropie_packages.sh $retropie_package $act
	done
done

##############################################################################
# auto start emulationstation
##############################################################################

mkdir -pv \
	$HOME/bin \
	$autostartdir

cp -v files/es_start $HOME/bin/
cp -v files/retropie.desktop $autostartdir/
cp -v files/retropie.desktop $HOME/Desktop/

chmod +x $HOME/bin/es_start

exit

#./retropie_packages.sh esthemes install_theme RetroCRT-240p xovox
